---
output:
  word_document:
    reference_docx: Research_CIA_my_style.docx
bibliography: StatEd.bib
csl: apa.csl
---
# Introduction

We encounter statistics and deal with it every now and then. Whether we are watching TV or reading the newspaper, we are confronted with statistical information in topics such as politics, economics, education, food, medicine, science and technology, sports, movies, public opinion, and social behavior. This is also true in our jobs and in the internet. We often than not make use of these information when we make choices and decisions. According to @franklin07, "statistical literacy can aid us in our daily personal choices." For example, when we decide to purchase a laptop, our knowledge in statistics would usually lead us to read and compare laptop specifications, reviews found in the internet and from colleagues, star ratings, and comments from those who purchased laptops. Otherwise, we end up buying a laptop that is not worth our money or a laptop that does not soothe our needs or even a laptop that is defective.

Government agencies also have statistics available for the public. These statistics are results from the analysis of their vast collection of data gathered in performing their operations. Board exam results, monthly number of dengue cases, the volume of traffic in highways during rush hours, monthly precipitation in millimeters, monthly income of households, population growth, the path of typhoons and national examination scores of elementary schools are just a few to mention. They also make use of various statistical methods to visualize, understand, learn and infer patterns, groupings, and behaviors from these data which are useful in creating statistical models, systems and solutions that will aide government and individual decision making. Statistics paved the way for the effective and efficient evidence-based policies which the government uses in pursuing its core responsibilities of economic prosperity, security, social cohesion and environmental sustainability.

Moreover, science and technology has evidently improved our lives. Information is easily available in the internet using our smartphones. Medical care and procedures have improved. Artificial intelligence is now being used in our computers and devices to give us ease of access. Statistics has played an immeasurable role in the development of science and technology. Statistics also ensures effectiveness and efficiency of inventions and discoveries.  

Hence statistical literacy is a very important factor in the growth and development of a country. According to @steen01 as cited in @franklin07, statistical literacy “empowers people by giving them tools to think for themselves, to ask intelligent questions of experts, and to confront authority confidently. These are skills required to survive in the modern world.”  Statistical literacy is of the essence and statistics education plays a very big role in instilling statistical literacy to individuals. According to @franklin07, it should be developed beginning in the elementary grades and strengthened through high school. She pointed out also that "an investment in statistical literacy is an investment in our nation’s economic future, as well as in the well-being of individuals."

This paper will define statistics education in the K to 12 curriculum of the Department of Education (DepEd) in the Philippines and in other countries. It will also discuss how the Philippine's curriculum compare with other countries' curriculum. It will also discuss established standards in implementing statistics education in the K to 12 curriculum.

# Presentation of Cases

## Statistics Education in the Philippines



# Summary and Conclusion

# References